// ─── DONNÉES EXEMPLES & VALEURS PAR DÉFAUT ────────────────────────────────────

export const CLIENT_VIDE = {
  nom: "",
  activite: "salarié",
  niveauRisque: "RM/RF",
  typeOperation: "souscription",
  produitVie: false,
  niveauRisqueElevé: false,
  capitalAssure: 0,
  prime: 0,
  paysGafi: false,
  valeurRachat: 0,
  augmentationCapital: 0,
  rachatMoins90j: false,
  beneficiairePaysRisque: false,
  changementBeneficiaire: false,
  baytIIcoherent: false,
  souscriptionsMultiples: false,
  paiementEspeces: 0,
  plusieursComptes: false,
};

export const EXEMPLES_CLIENTS = [
  {
    id: "CLI-001",
    nom: "Ahmed Ben Salah",
    activite: "étudiant",
    niveauRisque: "RM/RF",
    typeOperation: "souscription",
    produitVie: true,
    niveauRisqueElevé: false,
    capitalAssure: 60000,
    prime: 1200,
    paysGafi: false,
    valeurRachat: 0,
    augmentationCapital: 0,
    rachatMoins90j: false,
    beneficiairePaysRisque: false,
    changementBeneficiaire: false,
    baytIIcoherent: false,
    souscriptionsMultiples: false,
    paiementEspeces: 500,
    plusieursComptes: false,
  },
  {
    id: "CLI-002",
    nom: "Fatma Gharbi",
    activite: "chef d'entreprise",
    niveauRisque: "RE",
    typeOperation: "souscription",
    produitVie: true,
    niveauRisqueElevé: true,
    capitalAssure: 180000,
    prime: 2500,
    paysGafi: false,
    valeurRachat: 0,
    augmentationCapital: 1.5,
    rachatMoins90j: false,
    beneficiairePaysRisque: true,
    changementBeneficiaire: false,
    baytIIcoherent: false,
    souscriptionsMultiples: false,
    paiementEspeces: 0,
    plusieursComptes: false,
  },
  {
    id: "CLI-003",
    nom: "Karim Mansouri",
    activite: "fonctionnaire",
    niveauRisque: "RM/RF",
    typeOperation: "rachat",
    produitVie: false,
    niveauRisqueElevé: false,
    capitalAssure: 0,
    prime: 0,
    paysGafi: true,
    valeurRachat: 45000,
    augmentationCapital: 0,
    rachatMoins90j: true,
    beneficiairePaysRisque: false,
    changementBeneficiaire: true,
    baytIIcoherent: false,
    souscriptionsMultiples: false,
    paiementEspeces: 3500,
    plusieursComptes: false,
  },
];
